apiVersion: v1
kind: Service
metadata:
  name: {{ template "ejabberd.fullname" . }}
  labels:
    app: {{ template "ejabberd.name" . }}
    chart: {{ template "ejabberd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.c2s.port }}
      targetPort: c2s
      protocol: TCP
      name: c2s
    - port: {{ .Values.service.s2s.port }}
      targetPort: s2s
      protocol: TCP
      name: s2s
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpUpload.port }}
      targetPort: http-upload
      protocol: TCP
      name: http-upload
  selector:
    app: {{ template "ejabberd.name" . }}
    release: {{ .Release.Name }}
